name: Deploy on Firebase

on: 
    push:
        branches:
        - main

jobs:
  deploy_to_live:
    name: Deploy on Firebase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
    #   - name: Install Yarn
    #     run: npm install yarn@latest -g
      - name: Install Firebase Tools
        run: npm install firebase-tools -g
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting:${{ secrets.FIREBASE_HOSTING_ID }} -P ${{ secrets.FIREBASE_PROJECT_ID }}